export const RESEARCH_TAGS = [
  "visualization",
  "interaction",
  "urban-data",
  "imaging",
  "neuroanalytics",
  "data-systems",
  "reproducibility",
  "responsible-ai",
] as const;

export type ResearchTag = (typeof RESEARCH_TAGS)[number];

export const PROJECT_TAGS = [
  "dashboards",
  "multimodal",
  "sensemaking",
  "urban-computing",
  "soundscapes",
  "maps",
  "provenance",
  "workflows",
  "debugging",
  "explainability",
  "fairness",
  "evaluation",
  "simulation",
  "planning",
  "scenarios",
  "open-science",
  "infrastructure",
] as const;

export type ProjectTag = (typeof PROJECT_TAGS)[number];

export const PUBLICATION_TAGS = [
  "visualization",
  "databases",
  "machine-learning",
  "biomedical",
  "urban-data",
  "explainability",
  "reproducibility",
  "fairness",
  "data-management",
  "automl",
  "sports",
  "deep-learning",
  "public-health",
  "neuroimaging",
  "spatial-data",
  "gpu",
  "ranking",
  "medical-imaging",
  "segmentation",
  "natural-language",
  "covid-19",
  "health-disparities",
  "brain-development",
  "regulation",
  "web-data",
  "misinformation",
  "reinforcement-learning",
  "debugging",
  "sensors",
  "computer-vision",
  "social-media",
  "provenance",
  "stability",
  "clustering",
  "astronomy",
  "medical",
  "topology",
  "responsible-ai",
  "transparency",
  "biology",
  "geometry",
  "theory",
  "security",
  "dimensionality-reduction",
  "human-rights",
  "text-analysis",
  "dataflow",
  "privacy",
  "time-series",
  "art",
] as const;

export type PublicationTag = (typeof PUBLICATION_TAGS)[number];
